# Generated by Django 4.0.1 on 2022-01-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=32, unique=True)),
                ('time_opened', models.DateTimeField(auto_now_add=True)),
                ('time_last_seen', models.DateTimeField(auto_now=True)),
                ('time_closed', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'ordering': ['-time_last_seen'],
            },
        ),
    ]
