# Generated by Django 4.0.1 on 2022-03-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particle_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='particlesession',
            name='platform',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
