# Generated by Django 4.0.1 on 2022-02-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
