# Generated by Django 4.0.1 on 2022-02-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_time_subscription_form_succeeded'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCheckout',
            fields=[
                ('checkout_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('time_opened', models.DateTimeField(auto_now_add=True)),
                ('time_closed', models.DateTimeField(blank=True, default=None, null=True)),
                ('result', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('stripe_session_id', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
