# Generated by Django 4.0.1 on 2022-02-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pendingcheckout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_period_end',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
