# Generated by Django 4.0.1 on 2022-02-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_subscription_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
