# Generated by Django 4.0.1 on 2022-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_salt',
            field=models.CharField(default='THIS IS A BAD SALT!!', max_length=64),
            preserve_default=False,
        ),
    ]
